version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
      MSSQL_DB: yourdatabase
    ports:
      - "1434:1434"
    volumes:
      - db-data:/var/opt/mssql

volumes:
  db-data: